[project]
name = "reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "gradio>=5.29.0",
    "hf-transfer>=0.1.9",
    "kokoro>=0.9.4",
    "modal>=0.75.6",
    "torch>=2.7.0",
]
